import React from "react";
import Head from "next/head";

import MainPage from "components/Main";

export default function Home() {
  return (
    <>
      <Head>
        <title>Ai Automation Agency</title>
        <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=430" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <MainPage/>
    </>
  );
}
