import React from "react";
import Head from "next/head";


import Frame from "components/common/Frame";
import Header from "components/Main/Header";
import FirstPage from "components/Main/FirstPage";
import MainPage from "../components/Main";



export default function Home() {
  return (
    <>
      <Head>
        <title>Ai Automation Agency</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <MainPage/>
    </>
  );
}
